// Copyright (C) 2025  Altera Corporation. All rights reserved.
// Your use of Altera Corporation's design tools, logic functions 
// and other software and tools, and any partner logic 
// functions, and any output files from any of the foregoing 
// (including device programming or simulation files), and any 
// associated documentation or information are expressly subject 
// to the terms and conditions of the Altera Program License 
// Subscription Agreement, the Altera Quartus Prime License Agreement,
// the Altera IP License Agreement, or other applicable license
// agreement, including, without limitation, that your use is for
// the sole purpose of programming logic devices manufactured by
// Altera and sold by Altera or its authorized distributors.  Please
// refer to the Altera Software License Subscription Agreements 
// on the Quartus Prime software download page.


// Generated by Quartus Prime Version 25.1 (Build Build 1129 10/21/2025)
// Created on Mon Mar 30 20:02:46 2026

FSM FSM_inst
(
	.F(F_sig) ,	// input  F_sig
	.S_t(S_t_sig) ,	// input  S_t_sig
	.J1(J1_sig) ,	// input  J1_sig
	.J2(J2_sig) ,	// input  J2_sig
	.clock(clock_sig) ,	// input  clock_sig
	.rst_n(rst_n_sig) ,	// input  rst_n_sig
	.L(L_sig) ,	// output  L_sig
	.E(E_sig) ,	// output  E_sig
	.B(B_sig) ,	// output  B_sig
	.I1(I1_sig) ,	// output  I1_sig
	.I2(I2_sig) ,	// output  I2_sig
	.out_Q1(out_Q1_sig) ,	// output  out_Q1_sig
	.out_Q2(out_Q2_sig) ,	// output  out_Q2_sig
	.out_Q0(out_Q0_sig) 	// output  out_Q0_sig
);

